spring.application.name=smartsalud

# Supabase PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.ewnjysspttzypmfztfrw
spring.datasource.password=1oIunHqrkLb9qNzL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
# Usamos validate o none porque la DB ya está creada por el script SQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Evitamos que Hibernate intente usar features muy nuevas si no aplican
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Server Configuration
server.port=8080